<?php

namespace Leafwrap\RoleSanctions;

use Illuminate\Support\ServiceProvider;

class RoleSanctionServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->loadRoutesFrom(__DIR__ . '/routes/api.php');
        $this->loadMigrationsFrom(__DIR__ . '/database/migrations');

        $this->publishes([
            __DIR__ . '/migrations'                => $this->app->databasePath('migrations'),
            __DIR__ . '/config/role-sanctions.php' => config_path('role-sanctions.php'),
        ]);
    }

    public function register()
    {
        $this->registerFacades();
        parent::register(); // TODO: Change the autogenerated stub
    }

    protected function registerFacades()
    {
        $this->app->singleton('RoleSanction', function ($app) {
            return new RoleSanction();
        });
    }
}
